### ISSUE TITLE
(ql:quickload 'flamegraph) => System "flamegraph" not found

### ISSUE THREAD

**Issue by erjoalgo** [40ants/cl-flamegraph#2]
```
System "flamegraph" not found
   [Condition of type QUICKLISP-CLIENT:SYSTEM-NOT-FOUND]

Restarts:
 0: [CONTINUE] Try again
 1: [ABORT] Give up on "flamegraph"
 2: [RETRY] Retry SLIME REPL evaluation request.
 3: [*ABORT] Return to SLIME's top level.
 4: [ABORT] abort thread (#<THREAD "repl-thread" RUNNING {100647FF83}>)

Backtrace:
  0: ((LABELS QUICKLISP-CLIENT::RECURSE :IN QUICKLISP-CLIENT::COMPUTE-LOAD-STRATEGY) "flamegraph")
  1: (QL-DIST::CALL-WITH-CONSISTENT-DISTS #<CLOSURE (LAMBDA NIL :IN QUICKLISP-CLIENT::COMPUTE-LOAD-STRATEGY) {1005F19B8B}>)
  2: (QUICKLISP-CLIENT::COMPUTE-LOAD-STRATEGY "flamegraph")
  3: (QUICKLISP-CLIENT::AUTOLOAD-SYSTEM-AND-DEPENDENCIES "flamegraph" :PROMPT NIL)
  4: ((:METHOD QL-IMPL-UTIL::%CALL-WITH-QUIET-COMPILATION (T T)) #<unused argument> #<CLOSURE (FLET QUICKLISP-CLIENT::QL :IN QUICKLISP-CLIENT:QUICKLOAD) {1005F19AAB}>) [fast-method]
  5: ((:METHOD QL-IMPL-UTIL::%CALL-WITH-QUIET-COMPILATION :AROUND (QL-IMPL:SBCL T)) #<QL-IMPL:SBCL {1001141743}> #<CLOSURE (FLET QUICKLISP-CLIENT::QL :IN QUICKLISP-CLIENT:QUICKLOAD) {1005F19AAB}>) [fast-me..
  6: ((:METHOD QUICKLISP-CLIENT:QUICKLOAD (T)) FLAMEGRAPH :PROMPT NIL :SILENT NIL :VERBOSE NIL) [fast-method]
  7: (QL-DIST::CALL-WITH-CONSISTENT-DISTS #<CLOSURE (LAMBDA NIL :IN QUICKLISP-CLIENT:QUICKLOAD) {1005F09E8B}>)
  8: (SB-INT:SIMPLE-EVAL-IN-LEXENV (QUICKLISP-CLIENT:QUICKLOAD (QUOTE FLAMEGRAPH)) #<NULL-LEXENV>)
  9: (EVAL (QUICKLISP-CLIENT:QUICKLOAD (QUOTE FLAMEGRAPH)))
 --more--
```

**Comment by erjoalgo** [comment]
I didn't read the step to add `(ql-dist:install-dist "http://dist.ultralisp.org/" :prompt nil)`.

**Comment by hajovonta** [comment]
The readme still says "Or clone repository to your ~/quicklisp/local-projects folder."
It looks like this package is not loadable without Ultralisp now. (Which is not a problem, but I think the readme should reflect that)

Also, there is a dependency flamegraph/core, I'm not sure if there is a repo for that somewhere.

**Comment by svetlyak40wt** [comment]
This project is not in Quicklisp. Probably somebody should create an issue to add it here: https://github.com/quicklisp/quicklisp-projects

However, installation into `~/quicklisp/local-projects` should work anyway.

**Comment by svetlyak40wt** [comment]
Actually, this project needs some love. For example, it does not work on recent SBCL versions. @hajovonta if you have some time and motivation, you could investigate and try to fix these problems.

**Comment by hajovonta** [comment]
I cloned the repo to the local-projects folder, but ql still refuses to find it. I noticed there is no package.lisp,  maybe that's the reason.

**Comment by hajovonta** [comment]
I looked into the project, and I think it would be nice if we could make it completely native, e.g. avoid Perl tool dependency. SVG generation is entirely possible in CL.
