### ISSUE TITLE
Clarify variant of BSD license

### ISSUE THREAD

**Issue by arunisaac** [40ants/cl-flamegraph#9]
Hi,

Could you clarify the variant of BSD license cl-flamegraph is released under? Wikipedia lists at least 4 variants. https://en.wikipedia.org/wiki/BSD_licenses#Terms

Thanks!
Arun

**Comment by svetlyak40wt** [comment]
Thank you for the question. It is a BSD-3-Clause. I've updated ASDF definition accordingly.

**Comment by arunisaac** [comment]
Thank you!
